### ISSUE TITLE
change perms

### ISSUE THREAD

**Issue by tellok** [imba97/picgo-plugin-sftp-uploader#1]
images upload have defualt 600 perms, thus can't read by programs running under other uid besides ssh/scp user

**Comment by imba97** [comment]
什么意思，是权限问题吗。

**Comment by tellok** [comment]
是的，上传上来的文件默认是600权限（maybe 是用户umask配置的问题？）， 以其他用户运行的程序读取不了

**Comment by imba97** [comment]
目前的解决方案是上传图片的用户和使用图片的用户统一用一个
更改权限或者更改文件所属，理论上是可以远程执行一个命令的，下次更新我试试

**Comment by tellok** [comment]
多谢哈，
我一般用容器启动各种服务，在docker没有启用user namespace的情况下，有些服务改运行用户身份不方便

**Comment by imba97** [comment]
现在应该可以了，你可以在配置加上 fileUser 指定用户和用户组
