### ISSUE TITLE
求助：index.js引入模块问题

### ISSUE THREAD

**Issue by Yangbin-v** [imba97/picgo-plugin-sftp-uploader#2]
你好，我在引入crypto库后，picgo.log提示下面这个，是因为编译问题吗？crypto库是picgo里面有的吗？
打扰了。
---------------------分割线begin---------------------------
import crypto_ from 'crypto'
^^^^^^^

SyntaxError: Unexpected identifier
---------------------分割线end------------------

**Comment by imba97** [comment]
这句代码前后的代码是什么，报错应该是语法问题，少符号之类的

**Comment by Yangbin-v** [comment]
![image](https://user-images.githubusercontent.com/52195047/124603262-522edf00-de9c-11eb-81fe-626f6eb6932b.png)
![image](https://user-images.githubusercontent.com/52195047/124603401-7b4f6f80-de9c-11eb-8fe2-3b5757e75dc5.png)

编辑器没有报错哎

**Comment by Yangbin-v** [comment]
我把import 'crypto'换成require('crypto')就可以了，应该跟picgo插件加载机制有关系吧？
谢谢啦！

**Comment by imba97** [comment]
哦哦
跟加载机制应该没关系，picgo 应该只会引入，然后在合适的地方调用插件暴露出去的函数
我感觉是你`package.json`没加`"type":"module"`

**Comment by imba97** [comment]
不过我这个也没有，那就不清楚啥原因了
